steps:
- id: lint
  name: gcr.io/$PROJECT_ID/make
  args: [test]
  waitFor: ['-']
- id: tools/hive-bigquery
  name: google/cloud-sdk
  args: [gcloud, builds, submit, tools/hive-bigquery/, --config=tools/hive-bigquery/cloudbuild.yaml]
  waitFor: ['-']
- id: tools/hive-bigquery
  name: google/cloud-sdk
  args: [gcloud, builds, submit, examples/cloud-composer-examples/composer_http_post_example/,
    --config=examples/cloud-composer-examples/composer_http_post_example/cloudbuild.yaml]
  waitFor: ['-']

